# Generated by Django 6.1.1 on 2026-09-14 10:47

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('totp_secret_encrypted', core.fields.EncryptedCharField(blank=True, default='', max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login_at', null=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['email'],
            },
        ),
    ]
