# Generated by Django 6.1.1 on 2026-09-14 10:47

import django.db.models.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id', models.BigAutoField(db_column='planning_item_id', primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('GOAL', 'Goal'), ('TASK', 'Task'), ('ASSIGNMENT', 'Assignment')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('sibling_order', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('duration_category', models.CharField(blank=True, choices=[('UNDER_20_MIN', 'Under 20 minutes'), ('MIN_20_TO_60', '20 to 60 minutes'), ('OVER_60_MIN', 'Over 60 minutes')], max_length=12, null=True)),
                ('priority_position', models.PositiveIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('canvas_object_type', models.CharField(blank=True, choices=[('COURSE', 'Course'), ('ASSIGNMENT', 'Assignment')], max_length=10, null=True)),
                ('canvas_object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='planning.planningitem')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planning_items',
                'ordering': ['sibling_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentDetail',
            fields=[
                ('planning_item', models.OneToOneField(db_column='planning_item_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='assignment_detail', serialize=False, to='planning.planningitem')),
                ('weight_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mark_achieved', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('submission_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('marks_position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assignment_details',
                'ordering': ['marks_position'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(db_column='tag_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanningItemTag',
            fields=[
                ('id', models.BigAutoField(db_column='planning_item_tag_id', primary_key=True, serialize=False)),
                ('planning_item', models.ForeignKey(db_column='planning_item_id', on_delete=django.db.models.deletion.CASCADE, to='planning.planningitem')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='planning.tag')),
            ],
            options={
                'db_table': 'planning_item_tags',
            },
        ),
        migrations.AddField(
            model_name='planningitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='planning_items', through='planning.PlanningItemTag', to='planning.tag'),
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(db_column='timezone_id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timezones',
                'ordering': ['start_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_tag_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='planningitemtag',
            constraint=models.UniqueConstraint(fields=('planning_item', 'tag'), name='uniq_planning_item_tag'),
        ),
        migrations.AddConstraint(
            model_name='planningitem',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('user', 'priority_position'), name='uniq_user_priority_position'),
        ),
        migrations.AddConstraint(
            model_name='planningitem',
            constraint=models.UniqueConstraint(condition=models.Q(('canvas_object_id__isnull', False)), fields=('user', 'canvas_object_type', 'canvas_object_id'), name='uniq_canvas_object_per_user'),
        ),
        migrations.AddConstraint(
            model_name='planningitem',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='planning_item_no_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='planningitem',
            constraint=models.CheckConstraint(condition=models.Q(('priority_position__gte', 1), ('priority_position__isnull', True), _connector='OR'), name='planning_item_priority_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='timezone',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='timezone_end_not_before_start'),
        ),
    ]
