# Generated by Django 6.1.1 on 2026-09-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_planninghistoryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningitem',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
