# Generated by Django 6.1.1 on 2026-09-18 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_planningitem_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planningitem',
            name='priority_restore_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='planningitem',
            name='schedule_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planninghistoryentry',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('MOVE', 'Move'), ('COMPLETE', 'Complete'), ('PRIORITY', 'Priority'), ('SCHEDULE', 'Schedule')], max_length=10),
        ),
        migrations.AlterField(
            model_name='planningitem',
            name='duration_category',
            field=models.CharField(choices=[('UNDER_20_MIN', 'Under 20 minutes'), ('MIN_20_TO_60', '20 to 60 minutes'), ('OVER_60_MIN', 'Over 60 minutes')], default='MIN_20_TO_60', max_length=12),
        ),
        migrations.CreateModel(
            name='SchedulingOverload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('allowed', models.BooleanField(default=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_scheduling_overload_day')],
            },
        ),
        migrations.CreateModel(
            name='SchedulingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('under_20', models.PositiveSmallIntegerField(default=5)),
                ('minutes_20_to_60', models.PositiveSmallIntegerField(default=4)),
                ('over_60', models.PositiveSmallIntegerField(default=3)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user',), name='uniq_scheduling_preferences_user')],
            },
        ),
    ]
