# Generated by Django 6.1.1 on 2026-09-20 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_contract_foundations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scheduled_date', models.DateField()),
                ('execution_rank', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_allocations', to='planning.planningitem')),
            ],
            options={
                'db_table': 'planning_scheduler_allocations',
                'ordering': ['scheduled_date', 'execution_rank', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('percentage__gt', 0), ('percentage__lte', 100)), name='scheduler_allocation_percentage_range')],
            },
        ),
    ]
