# Generated by Django 6.1.1 on 2026-09-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_schedulerallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningitem',
            name='deletion_restore_context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
