# Generated by Django 6.1.1 on 2026-09-20 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_planningitem_deletion_restore_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='planningitem',
            constraint=models.CheckConstraint(condition=models.Q(('percent_completed__gte', 0), ('percent_completed__lte', 100)), name='planning_item_percent_completed_range'),
        ),
        migrations.AddConstraint(
            model_name='progresssegment',
            constraint=models.CheckConstraint(condition=models.Q(('is_completed', True)), name='progress_segment_must_be_confirmed'),
        ),
    ]
