# Generated by Django 6.1.1 on 2026-09-20 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_planningitem_planning_item_percent_completed_range_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planningitem',
            name='uniq_user_priority_position',
        ),
        migrations.AddConstraint(
            model_name='planningitem',
            constraint=models.UniqueConstraint(fields=('user', 'priority_position'), name='uniq_user_priority_position'),
        ),
    ]
