# Generated by Django 6.1.1 on 2026-09-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_remove_planningitem_uniq_user_priority_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningitem',
            name='expired_manual_requested_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
