# Generated by Django 6.1.1 on 2026-09-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_planningitem_expired_manual_requested_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningitem',
            name='execution_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
