# Generated by Django 6.1.1 on 2026-09-21 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_planningitem_execution_rank'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedulingpreference',
            name='uniq_scheduling_preferences_user',
        ),
        migrations.RemoveField(
            model_name='planningitem',
            name='schedule_is_manual',
        ),
        migrations.DeleteModel(
            name='SchedulingPreference',
        ),
    ]
