# Generated by Django 6.1.1 on 2026-09-14 10:47

import core.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasConnection',
            fields=[
                ('id', models.BigAutoField(db_column='canvas_connection_id', primary_key=True, serialize=False)),
                ('api_token_encrypted', core.fields.EncryptedCharField(max_length=500)),
                ('canvas_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='canvas_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'canvas_connections',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(db_column='sync_log_id', primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=7)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ['-started_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['SUCCESS', 'FAILED'])), name='sync_log_status_valid')],
            },
        ),
    ]
