"""C7.4c fresh-seed development-confirmation utilities."""
from __future__ import annotations

from dataclasses import dataclass, replace
from pathlib import Path
from types import MappingProxyType

from arena.experiments.paired import (
    _config_json,
    _dump,
    _normalize,
)
from arena.experiments.v1_runner import V1RunConfig

from .execution import (
    TuningCandidateSummary,
    TuningStudyResults,
    TuningTrialObservation,
)
from .racing_execution import _rebuild_summary
from .study import (
    TuningCandidate,
    TuningStudyPlan,
)


@dataclass(frozen=True, slots=True)
class ConfirmationCandidateLink:
    source_candidate_id: str
    confirmation_candidate_id: str


@dataclass(frozen=True, slots=True)
class ConfirmationExecutionPlan:
    tuning_plan: TuningStudyPlan
    candidate_links: tuple[
        ConfirmationCandidateLink,
        ...
    ]


def _candidate_semantic_key(
    candidate: TuningCandidate,
) -> str:
    improver_config = None

    if candidate.improver.engine is not None:
        improver_config = _config_json(
            candidate.improver.engine
        )

    payload = {
        'comparison_objective':
            _normalize(
                candidate.comparison_objective
            ),
        'constructor_config':
            _config_json(
                candidate.constructor.algorithm
            ),
        'improver_config':
            improver_config,
    }

    return _dump(payload)


def build_confirmation_subset_plan(
    source_full_plan: TuningStudyPlan,
    fresh_seed_full_plan: TuningStudyPlan,
    *,
    source_candidate_ids: tuple[str, ...],
    scenario_ids: tuple[str, ...],
    output_root: Path,
    trial_wall_seconds: float,
) -> ConfirmationExecutionPlan:
    """Build fresh-seed execution for frozen source candidates.

    The fresh full plan is independently generated by the normal C7 planner
    using the confirmation seed set. Frozen source candidates are matched to
    fresh-seed candidates by semantic configuration, never by stale
    seed-dependent candidate or improver IDs.
    """
    if not isinstance(
        source_full_plan,
        TuningStudyPlan,
    ):
        raise TypeError(
            'source_full_plan must be TuningStudyPlan'
        )

    if not isinstance(
        fresh_seed_full_plan,
        TuningStudyPlan,
    ):
        raise TypeError(
            'fresh_seed_full_plan must be TuningStudyPlan'
        )

    if not isinstance(output_root, Path):
        raise TypeError(
            'output_root must be Path'
        )

    if (
        source_full_plan.benchmark_manifest_sha256
        != fresh_seed_full_plan.benchmark_manifest_sha256
    ):
        raise ValueError(
            'Benchmark identity changed for confirmation'
        )

    if (
        source_full_plan.development_scenario_ids
        != fresh_seed_full_plan.development_scenario_ids
        or source_full_plan.holdout_scenario_ids
        != fresh_seed_full_plan.holdout_scenario_ids
    ):
        raise ValueError(
            'Development/holdout partition changed '
            'for confirmation'
        )

    if (
        not isinstance(source_candidate_ids, tuple)
        or not source_candidate_ids
        or len(set(source_candidate_ids))
        != len(source_candidate_ids)
    ):
        raise ValueError(
            'source_candidate_ids must be a '
            'unique nonempty tuple'
        )

    if (
        not isinstance(scenario_ids, tuple)
        or not scenario_ids
        or len(set(scenario_ids))
        != len(scenario_ids)
    ):
        raise ValueError(
            'scenario_ids must be a unique '
            'nonempty tuple'
        )

    if (
        set(scenario_ids)
        - set(
            source_full_plan.development_scenario_ids
        )
    ):
        raise ValueError(
            'Confirmation scenario escaped '
            'development partition'
        )

    if (
        set(scenario_ids)
        & set(source_full_plan.holdout_scenario_ids)
    ):
        raise ValueError(
            'Confirmation attempted to access holdout'
        )

    if (
        set(source_full_plan.spec.seeds)
        & set(fresh_seed_full_plan.spec.seeds)
    ):
        raise ValueError(
            'Fresh confirmation seeds must be disjoint '
            'from historical tuning seeds'
        )

    source_by_id = {
        candidate.candidate_id: candidate
        for candidate in source_full_plan.candidates
    }

    try:
        source_candidates = tuple(
            source_by_id[candidate_id]
            for candidate_id
            in source_candidate_ids
        )
    except KeyError as exc:
        raise ValueError(
            'Unknown frozen source candidate'
        ) from exc

    fresh_by_semantic_key = {}

    for candidate in fresh_seed_full_plan.candidates:
        key = _candidate_semantic_key(
            candidate
        )

        if key in fresh_by_semantic_key:
            raise ValueError(
                'Fresh confirmation plan has duplicate '
                'semantic candidate configuration'
            )

        fresh_by_semantic_key[key] = candidate

    fresh_candidates = []
    links = []

    for source in source_candidates:
        key = _candidate_semantic_key(
            source
        )

        fresh = fresh_by_semantic_key.get(
            key
        )

        if fresh is None:
            raise ValueError(
                'Frozen survivor has no matching '
                'fresh-seed candidate'
            )

        fresh_candidates.append(
            fresh
        )

        links.append(
            ConfirmationCandidateLink(
                source_candidate_id=
                    source.candidate_id,
                confirmation_candidate_id=
                    fresh.candidate_id,
            )
        )

    fresh_candidates = tuple(
        fresh_candidates
    )

    if len({
        candidate.candidate_id
        for candidate in fresh_candidates
    }) != len(fresh_candidates):
        raise ValueError(
            'Fresh confirmation candidate IDs '
            'are not unique'
        )

    grouped = {}

    for candidate in fresh_candidates:
        key = (
            candidate.objective_id,
            candidate.constructor.arm_id,
        )

        grouped.setdefault(
            key,
            [],
        ).append(candidate)

    runs = []

    for index, group_candidates in enumerate(
        grouped.values(),
        start=1,
    ):
        first = group_candidates[0]

        if any(
            candidate.objective_id
            != first.objective_id
            or candidate.constructor.arm_id
            != first.constructor.arm_id
            or candidate.comparison_objective
            != first.comparison_objective
            for candidate in group_candidates
        ):
            raise ValueError(
                'Invalid confirmation execution group'
            )

        improvers = tuple(
            candidate.improver
            for candidate in group_candidates
        )

        if len({
            improver.arm_id
            for improver in improvers
        }) != len(improvers):
            raise ValueError(
                'Duplicate confirmation improver'
            )

        runs.append(
            V1RunConfig(
                scenario_ids=scenario_ids,
                constructors=(
                    first.constructor,
                ),
                improvers=improvers,
                seeds=
                    fresh_seed_full_plan.spec.seeds,
                comparison_objective=
                    first.comparison_objective,
                trial_wall_seconds=
                    trial_wall_seconds,
                output_dir=(
                    output_root
                    / (
                        f'group_{index:02d}_'
                        f'{first.constructor.arm_id[:24]}'
                    )
                ),
            )
        )

    expected_trials = (
        len(fresh_candidates)
        * len(scenario_ids)
        * len(
            fresh_seed_full_plan.spec.seeds
        )
    )

    represented = {
        (
            _dump(
                _normalize(
                    run.comparison_objective
                )
            ),
            run.constructors[0].arm_id,
            improver.arm_id,
        )
        for run in runs
        for improver in run.improvers
    }

    expected_representation = {
        (
            _dump(
                _normalize(
                    candidate.comparison_objective
                )
            ),
            candidate.constructor.arm_id,
            candidate.improver.arm_id,
        )
        for candidate in fresh_candidates
    }

    if represented != expected_representation:
        raise ValueError(
            'Confirmation groups do not represent '
            'exactly the requested candidates'
        )

    spec = replace(
        fresh_seed_full_plan.spec,
        output_root=output_root,
        trial_wall_seconds=
            trial_wall_seconds,
        max_candidates=
            len(fresh_candidates),
        max_trials=expected_trials,
    )

    tuning_plan = TuningStudyPlan(
        spec=spec,
        benchmark_manifest_sha256=
            fresh_seed_full_plan
            .benchmark_manifest_sha256,
        development_scenario_ids=
            scenario_ids,
        holdout_scenario_ids=
            fresh_seed_full_plan
            .holdout_scenario_ids,
        candidates=fresh_candidates,
        run_configs=tuple(runs),
        expected_trials=expected_trials,
    )

    return ConfirmationExecutionPlan(
        tuning_plan=tuning_plan,
        candidate_links=tuple(links),
    )


def relabel_confirmation_results(
    results: TuningStudyResults,
    candidate_links: tuple[
        ConfirmationCandidateLink,
        ...
    ],
) -> TuningStudyResults:
    """Map fresh-seed execution IDs back to frozen C7.4b source IDs."""
    if not isinstance(
        results,
        TuningStudyResults,
    ):
        raise TypeError(
            'results must be TuningStudyResults'
        )

    if (
        not isinstance(candidate_links, tuple)
        or not candidate_links
        or any(
            not isinstance(
                link,
                ConfirmationCandidateLink,
            )
            for link in candidate_links
        )
    ):
        raise ValueError(
            'candidate_links must be a nonempty '
            'tuple of ConfirmationCandidateLink'
        )

    confirmation_ids = tuple(
        link.confirmation_candidate_id
        for link in candidate_links
    )

    source_ids = tuple(
        link.source_candidate_id
        for link in candidate_links
    )

    if (
        len(set(confirmation_ids))
        != len(confirmation_ids)
        or len(set(source_ids))
        != len(source_ids)
    ):
        raise ValueError(
            'Confirmation/source candidate mapping '
            'must be one-to-one'
        )

    observed_ids = tuple(
        summary.candidate_id
        for summary in results.candidate_summaries
    )

    if observed_ids != confirmation_ids:
        raise ValueError(
            'Fresh result candidate order differs '
            'from confirmation mapping'
        )

    mapping = {
        link.confirmation_candidate_id:
            link.source_candidate_id
        for link in candidate_links
    }

    summaries = tuple(
        replace(
            summary,
            candidate_id=
                mapping[summary.candidate_id],
        )
        for summary in results.candidate_summaries
    )

    observations = tuple(
        replace(
            observation,
            candidate_id=
                mapping[observation.candidate_id],
        )
        for observation in results.trial_observations
    )

    return TuningStudyResults(
        output_root=results.output_root,
        benchmark_manifest_sha256=
            results.benchmark_manifest_sha256,
        development_scenario_ids=
            results.development_scenario_ids,
        holdout_scenario_ids=
            results.holdout_scenario_ids,
        seeds=results.seeds,
        candidate_summaries=summaries,
        trial_observations=observations,
        expected_trials=results.expected_trials,
        completed_trials=results.completed_trials,
    )


def combine_seed_tuning_results(
    historical: TuningStudyResults,
    fresh: TuningStudyResults,
    *,
    candidate_ids: tuple[str, ...],
) -> TuningStudyResults:
    """Pool disjoint seed replications over the same paired scenarios."""
    if not isinstance(
        historical,
        TuningStudyResults,
    ) or not isinstance(
        fresh,
        TuningStudyResults,
    ):
        raise TypeError(
            'Expected TuningStudyResults inputs'
        )

    if (
        historical.benchmark_manifest_sha256
        != fresh.benchmark_manifest_sha256
    ):
        raise ValueError(
            'Benchmark changed across confirmation seeds'
        )

    if (
        historical.development_scenario_ids
        != fresh.development_scenario_ids
        or historical.holdout_scenario_ids
        != fresh.holdout_scenario_ids
    ):
        raise ValueError(
            'Scenario partition changed across '
            'confirmation seeds'
        )

    if (
        set(historical.seeds)
        & set(fresh.seeds)
    ):
        raise ValueError(
            'Confirmation seed sets must be disjoint'
        )

    if (
        not isinstance(candidate_ids, tuple)
        or not candidate_ids
        or len(set(candidate_ids))
        != len(candidate_ids)
    ):
        raise ValueError(
            'candidate_ids must be unique '
            'and nonempty'
        )

    for results in (
        historical,
        fresh,
    ):
        result_ids = tuple(
            summary.candidate_id
            for summary
            in results.candidate_summaries
        )

        if result_ids != candidate_ids:
            raise ValueError(
                'Candidate order changed across '
                'confirmation evidence'
            )

    combined_seeds = (
        historical.seeds
        + fresh.seeds
    )

    observation_map = {}

    for results in (
        historical,
        fresh,
    ):
        for observation in (
            results.trial_observations
        ):
            key = (
                observation.candidate_id,
                observation.scenario_id,
                observation.run_seed,
            )

            if key in observation_map:
                raise ValueError(
                    'Duplicate candidate/scenario/seed '
                    'confirmation observation'
                )

            observation_map[key] = observation

    observations = []

    for candidate_id in candidate_ids:
        for scenario_id in (
            historical.development_scenario_ids
        ):
            for seed in combined_seeds:
                key = (
                    candidate_id,
                    scenario_id,
                    seed,
                )

                observation = (
                    observation_map.get(key)
                )

                if observation is None:
                    raise ValueError(
                        'Pooled confirmation evidence '
                        'is not a complete paired matrix'
                    )

                observations.append(
                    observation
                )

    historical_summaries = {
        summary.candidate_id: summary
        for summary
        in historical.candidate_summaries
    }

    summaries = []

    for candidate_id in candidate_ids:
        candidate_observations = tuple(
            observation
            for observation in observations
            if observation.candidate_id
            == candidate_id
        )

        summaries.append(
            _rebuild_summary(
                historical_summaries[
                    candidate_id
                ],
                candidate_observations,
            )
        )

    expected_trials = (
        len(candidate_ids)
        * len(
            historical.development_scenario_ids
        )
        * len(combined_seeds)
    )

    if len(observations) != expected_trials:
        raise ValueError(
            'Pooled confirmation trial '
            'cardinality mismatch'
        )

    return TuningStudyResults(
        output_root=fresh.output_root,
        benchmark_manifest_sha256=
            fresh.benchmark_manifest_sha256,
        development_scenario_ids=
            fresh.development_scenario_ids,
        holdout_scenario_ids=
            fresh.holdout_scenario_ids,
        seeds=combined_seeds,
        candidate_summaries=tuple(summaries),
        trial_observations=tuple(observations),
        expected_trials=expected_trials,
        completed_trials=expected_trials,
    )
